#!/bin/sh
#/ Usage: vim-arduino [-dc]
#/ Invokes the ino command that corresponds to the given flag ( (d)eploy or (c)ompile )
#/

# show usage
[ $# -eq 0 -o "$1" = "--help" ] && {
    grep '^#/'< "$0" | cut -c4-
    exit 2
}

command=""
correct_dir_structure=false
port_available=false


if [ -z $(ls /dev/tty.* | grep usb) ]
then
  exit 1
fi

while [ $(basename `pwd`) != '/' ]
do
  if [ $(basename `pwd`) == 'src' ] || [ $(basename `pwd`) == 'lib' ]
  then
    correct_dir_structure=true
    cd ..
    break
  elif [ $(ls | egrep "lib|src" | wc -l) -eq 2 ]
  then
    correct_dir_structure=true
    break
  fi

  cd ..
done

if ! $correct_dir_structure
then
  exit 1
fi

while [ $# -gt 0 ]
do
    case "$1" in
        -d|--deploy)
            command="ino build && ino upload"
            shift
            ;;
        -c|--compile)
            command="ino build"
            shift
            ;;
    esac
done

if [ "$command" != "" ]
then
  eval $command
else
  exit 1
fi

