#!/bin/sh

echo "use Ctrl-a, k to exit the screen utility"

port=$(ls /dev/tty.* | grep usb)

osascript -e \
  "tell application \"iTerm\"
    activate
    set myterm to (current terminal)
    tell myterm
      set mysession to (make new session at the end of sessions)
      tell mysession
        exec command \"/bin/bash -l\"
        write text \"screen $port\"
      end tell
    end tell
   end tell"
