#!/bin/sh
#/ Usage: vim-arduino [-dc]
#/ Invokes the ino command that corresponds to the given flag ( (d)eploy or (c)ompile )
#/

# show usage
[ $# -eq 0 -o "$1" = "--help" ] && {
    grep '^#/'< "$0" | cut -c4-
    exit 2
}

command=""

while [ $# -gt 0 ]
do
    case "$1" in
        -d|--deploy)
            command="ino build && ino upload"
            shift
            ;;
        -c|--compile)
            command="ino build"
            shift
            ;;
    esac
done

if [ "$command" != "" ]
then
  eval $command
else
  exit 1
fi

